#!/usr/bin/env python3
"""Regenerate scriptorium/_langtable.py from the ISO 639-2 registry.

    python scripts/gen_langs.py > scriptorium/_langtable.py

The registry is pipe-delimited:
    alpha3-bibliographic | alpha3-terminologic | alpha2 | English | French
"""

import sys
import urllib.request

URL = "https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt"

# Whisper's own codes, from faster_whisper.tokenizer._LANGUAGE_CODES. Kept
# static so validation never needs the inference stack imported.
WHISPER = [
    "af", "am", "ar", "as", "az", "ba", "be", "bg", "bn", "bo", "br", "bs",
    "ca", "cs", "cy", "da", "de", "el", "en", "es", "et", "eu", "fa", "fi",
    "fo", "fr", "gl", "gu", "ha", "haw", "he", "hi", "hr", "ht", "hu", "hy",
    "id", "is", "it", "ja", "jw", "ka", "kk", "km", "kn", "ko", "la", "lb",
    "ln", "lo", "lt", "lv", "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt",
    "my", "ne", "nl", "nn", "no", "oc", "pa", "pl", "ps", "pt", "ro", "ru",
    "sa", "sd", "si", "sk", "sl", "sn", "so", "sq", "sr", "su", "sv", "sw",
    "ta", "te", "tg", "th", "tk", "tl", "tr", "tt", "uk", "ur", "uz", "vi",
    "yi", "yo", "yue", "zh",
]

# Codes Whisper knows that the ISO 639-2 registry does not carry, or carries
# under a different primary code.
EXTRA = {
    "yue": "Cantonese",     # ISO 639-3 only
    "jw": "Javanese",       # Whisper's spelling; ISO 639-1 is jv
}


def main():
    req = urllib.request.Request(URL, headers={"User-Agent": "scriptorium gen_langs"})
    raw = urllib.request.urlopen(req, timeout=60).read().decode("utf-8-sig")

    names = {}
    alias = {}
    for line in raw.splitlines():
        if not line.strip():
            continue
        bib, term, two, english, _ = (line.split("|") + [""] * 5)[:5]
        name = english.split(";")[0].strip()
        if not name:
            continue
        canonical = two.strip() or bib.strip()
        if not canonical:
            continue
        names[canonical] = name
        for three in (bib.strip(), term.strip()):
            if three and three != canonical:
                alias[three] = canonical

    names.update(EXTRA)
    alias.setdefault("jav", "jw")

    out = sys.stdout.write
    out('"""Generated by scripts/gen_langs.py. Do not edit by hand."""\n\n')
    out("# Canonical code -> English name.\n")
    out("NAMES = {\n")
    for k in sorted(names):
        out(f"    {k!r}: {names[k]!r},\n")
    out("}\n\n")
    out("# Three-letter ISO 639-2 code -> canonical code.\n")
    out("ALIAS = {\n")
    for k in sorted(alias):
        if alias[k] in names:
            out(f"    {k!r}: {alias[k]!r},\n")
    out("}\n\n")
    out("# Languages Whisper can transcribe.\n")
    out("WHISPER = frozenset({\n")
    for c in sorted(WHISPER):
        out(f"    {c!r},\n")
    out("})\n")


if __name__ == "__main__":
    main()
